name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.24']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Verify dependencies
        run: go mod verify

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -v -o caws${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Verify binary
        if: matrix.os != 'windows-latest'
        run: ./caws --help || true

      - name: Verify binary (Windows)
        if: matrix.os == 'windows-latest'
        run: .\caws.exe --help || echo "Binary created successfully"
        shell: pwsh
